"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const controller_1 = require("./controller");
const middleware_1 = require("./middleware");
const router = express.Router();
router.post('/register', controller_1.register);
router.post('/login', controller_1.login);
router.get('/current', middleware_1.isAuthenticate, controller_1.getCurrentUser);
router.delete('/logout', middleware_1.isAuthenticate, controller_1.logout);
module.exports = router;
